spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://drinkio-db:3306/drinkio
    username: drinkio
    password: drinkio

springdoc:
  api-docs:
    path: /api-docs