spring:
  datasource:
  driver-class-name: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:mem:db
  username: sa
  password: sa
  jpa:
    open-in-view: false

springdoc:
  api-docs:
    path: /api-docs